config/routes.rb
      post 'restore', to: 'mail_service_rules#restore'
      post 'permanent_delete', to: 'mail_service_rules#permanent_delete'
      get 'search_courier_services', to: 'mail_service_rules#courier_servies'
    end
  end
  resources :seasons do
    collection do
      post 'import', to: 'seasons#import'
      post 'bulk_method', to: 'seasons#bulk_method'
      get 'archive', to: 'seasons#archive'
      post 'restore', to: 'seasons#restore'
      post 'permanent_delete', to: 'seasons#permanent_delete'
      post 'season_by_name', to: 'seasons#search_season_by_name'
    end
  end
  devise_for :users
  resources :users, except: [:create] do
    collection do
      post 'user_create', to: 'users#create'
      post 'import', to: 'users#import'
      post 'bulk_method', to: 'users#bulk_method'
      get 'archive', to: 'users#archive'
      post 'restore', to: 'users#restore'
    end
  end

  resources :products do
    collection do
      get 'version', to: 'products#version'
      post 'import', to: 'products#import'
      post 'bulk_method', to: 'products#bulk_method'
      get 'archive', to: 'products#archive'
      post 'restore', to: 'products#restore'
      post 'permanent_delete', to: 'products#permanent_delete'
      post 'products_by_title', to: 'products#search_products_by_title'
      post 'search_multipack', to: 'products#search_multipack'
      post 'products_by_sku', to: 'products#search_products_by_sku'
      post 'check_category', to: 'products#search_category'
      get 'export', to: 'products#export_logs'
    end
  end

  resources :categories do
    collection do
      post 'import', to: 'categories#import'
      get 'version', to: 'categories#version'
      post 'bulk_method', to: 'categories#bulk_method'
      get 'archive', to: 'categories#archive'
      post 'restore', to: 'categories#restore'
      post 'permanent_delete', to: 'categories#permanent_delete'
      post 'category_by_title', to: 'categories#search_category_by_title'
    end
  end

  resources :purchase_orders do
    collection do
      post 'import', to: 'purchase_orders#import'
      post 'bulk_method', to: 'purchase_orders#bulk_method'
      get 'archive', to: 'purchase_orders#archive'
      post 'restore', to: 'purchase_orders#restore'
      post 'send_email', to: 'purchase_orders#send_mail_to_supplier'
      post 'add_product', to: 'purchase_orders#add_product'
    end
    member do
      get 'quick_edit', to: 'purchase_orders#quick_edit'
    end
  end

  resources :purchase_deliveries do
    collection do
      post 'import', to: 'purchase_deliveries#import'
      post 'bulk_method', to: 'purchase_deliveries#bulk_method'
      get 'archive', to: 'purchase_deliveries#archive'
      post 'restore', to: 'purchase_deliveries#restore'
      post 'permanent_delete', to: 'purchase_deliveries#permanent_delete'
    end
  end

  resources :system_users do
    collection do
      post 'import', to: 'system_users#import'
      get 'version', to: 'system_users#version'
      post 'bulk_method', to: 'system_users#bulk_method'
      get 'archive', to: 'system_users#archive'
      post 'restore', to: 'system_users#restore'
      post 'system_user_by_name', to: 'system_users#search_system_user_by_name'
      post 'import_supplier_products', to: 'system_users#import_supplier_products'
    end
  end

  get '/home', to: 'home#dashboard'
  get '/settings', to: 'settings#index'

  resources :product_mappings do
    collection do
      post 'import', to: 'product_mappings#import'
      get 'version', to: 'product_mappings#version'
    end
  end
  resources :extra_field_names
  resources :order_dispatches do
    collection do
      get 'version', to: 'order_dispatches#version'
      post 'import', to: 'order_dispatches#import'
      get 'bulk_method', to: 'order_dispatches#bulk_method'
      post 'assign_rule', to: 'order_dispatches#assign_rule'
      get 'bulk_assign_rule', to: 'order_dispatches#bulk_assign_rule'
      get 'update_selected', to: 'order_dispatches#update_selected'
      get 'bulk_update_selected', to: 'order_dispatches#bulk_update_selected'
      get 'refresh', to: 'order_dispatches#refresh'
      get 'refresh_product', to: 'order_dispatches#refresh_product'
      get 'allocations', to: 'order_dispatches#allocations'
      post 'import_customer', to: 'order_dispatches#import_customer'
      get 'recalculate_rule', to: 'order_dispatches#recalculate_rule'
      get 'invoice', to: 'order_dispatches#invoice'
      get 'cancel_order', to: 'order_dispatches#cancel_order'
    end
  end

  resources :customers do
    collection do
      get 'version', to: 'customers#version'
      post 'add_flagging', to: 'customers#flagging_date'
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
    end
  end

  resources :pick_and_packs do
    collection do
      post 'import', to: 'pick_and_packs#import'
      post 'bulk_method', to: 'pick_and_packs#bulk_method'
      post 'assign_user', to: 'pick_and_packs#assign_user'
      get 'show_order', to: 'pick_and_packs#show_order'
      get 'start_packing', to: 'pick_and_packs#start_packing'
      post 'courier_edit', to: 'pick_and_packs#courier_edit'
      post 'address_edit', to: 'pick_and_packs#address_edit'
      get 'archive', to: 'pick_and_packs#archive'
      post 'restore', to: 'pick_and_packs#restore'
      post 'permanent_delete', to: 'pick_and_packs#permanent_delete'
      post 'season_by_name', to: 'pick_and_packs#search_season_by_name'
      get 'pick_all_items', to: 'pick_and_packs#pick_all_items'
      get 'scan_barcode', to: 'pick_and_packs#scan_barcode'
      get 'print_packing_list', to: 'pick_and_packs#print_packing_list'
      get 'download_pdf', to: 'pick_and_packs#download_pdf'
      get 'consignement', to: 'pick_and_packs#consignement'
    end
  end

  resources :order_batches do
    collection do
      get 'save_batch_name', to: 'order_batches#save_batch_name'
      post 'search_batch', to: 'order_batches#search_batch'
      get 'set_pick_preset', to: 'order_batches#set_pick_preset'
    end
  end

  resources :channel_forecastings do
    collection do
      get 'buffer_rule', to: 'channel_forecastings#buffer_rule'
      post 'assign_buffer_rule', to: 'channel_forecastings#assign_buffer_rule'
    end
  end

  resources :sellings do
    collection do
      get 'ebay_selling', to: 'sellings#ebay_selling'
    end
  end

  resources :mails
  resources :notes
  resources :inventory_reports do
    collection do
      get 'date_picker_from_to', to: 'inventory_reports#date_picker_from_to'
    end
  end

  resources :rules
  resources :job_statuses
  resources :transaction_reports do
    collection do
      get 'date_picker_from_to', to: 'transaction_reports#date_picker_from_to'
    end
  end

  resources :dispatch_reports do
    collection do
      get 'date_picker_from_to', to: 'dispatch_reports#date_picker_from_to'
    end
  end

  post 'product_file', to: 'products#import_product_file'
  post 'channel_product_file', to: 'product_mappings#import_product_file'
  post 'order_file', to: 'order_dispatches#import_order_file'
  post 'multi_file', to: 'import_mappings#multi_file_mapping'
  post 'courier_csv_export', to: 'import_mappings#courier_csv_export'
  post 'tracking_file', to: 'import_mappings#tracking_file'
  post 'consolidation_tool', to: 'import_mappings#consolidation_tool'
  get 'consolidation_tool_index', to: 'import_mappings#consolidation_tool_index'
  post 'competitive_price', to: 'import_mappings#competitive_price'
  get 'export_new_consolidation', to: 'import_mappings#export_new_consolidation'
  post 'export_new_consolidation', to: 'import_mappings#export_consolidation'
  post 'consolidation_mapping', to: 'import_mappings#consolidation_mapping'
  get 'download', to: 'import_mappings#download'
  post 'auto_dispatch', to: 'import_mappings#auto_dispatch'
  get 'new_auto_dispatch', to: 'import_mappings#new_auto_dispatch'
  get 'edit_auto_dispatch', to: 'import_mappings#edit_auto_dispatch'

  # Order Dispatch Routes
  get 'all_order_data', to: 'order_dispatches#all_order_data'
  get 'get_response_orders', to: 'order_dispatches#get_response_orders'

  # selected for all
  get 'update_selected', to: 'application#update_selected'
  get 'bulk_update_selected', to: 'application#bulk_update_selected'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#dashboard'

  # Dashboard Routes
  get '/dashboard/sales', to: 'dashboards#sales', as: :dashboard_sales
  get '/dashboard/ecommerce', to: 'dashboards#ecommerce', as: :dashboard_ecommerce
  get '/dashboard/analytics', to: 'dashboards#analytics', as: :dashboard_analytics
  get '/dashboard/crm', to: 'dashboards#crm', as: :dashboard_crm
  get '/dashboard/project', to: 'dashboards#project', as: :dashboard_project
  get '/dashboard/search', to: 'dashboards#search', as: :dashboard_search

  # Discussions Routes
  get '/discussions/inbox', to: 'discussions#inbox', as: :discussions_inbox
  get '/discussions/chat', to: 'discussions#chat', as: :discussions_chat

  # Todos Routes
  get '/todos/lists', to: 'todos#lists', as: :todos_lists
  get '/todos/notes', to: 'todos#notes', as: :todos_notes

  # UI Components Routes
  get '/ui_components/ui_alerts', to: 'ui_components#ui_alerts', as: :ui_alerts
  get '/ui_components/ui_badges', to: 'ui_components#ui_badges', as: :ui_badges
  get '/ui_components/ui_buttons', to: 'ui_components#ui_buttons', as: :ui_buttons
  get '/ui_components/ui_cards', to: 'ui_components#ui_cards', as: :ui_cards
  get '/ui_components/ui_dropdowns', to: 'ui_components#ui_dropdowns', as: :ui_dropdowns
  get '/ui_components/ui_forms', to: 'ui_components#ui_forms', as: :ui_forms
  get '/ui_components/ui_list_groups', to: 'ui_components#ui_list_groups', as: :ui_list_groups

app/controllers/home_controller.rb
# frozen_string_literal: true

# dashboard
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :load_products, :load_suppliers, :load_purchase_order, :load_deliveries, only: %i[dashboard]

  def dashboard
    @total_counts = { products_count: Product.count, suppliers_count: SystemUser.count,
                      purchase_orders_count: PurchaseOrder.count, purchase_deliveries_count: PurchaseDelivery.count }
  end

  def load_products
    @products = Product.ransack(params[:q]).result(distinct: true)
                       .order(created_at: :desc).page(params[:product_page]).per(5)
  end

  def load_suppliers
    @suppliers = SystemUser.suppliers.ransack(params[:q]).result(distinct: true)
                           .order(created_at: :desc).page(params[:supplier_page]).per(5)
  end

  def load_purchase_order
    @purchase_orders = PurchaseOrder.ransack(params[:q]).result(distinct: true)
                                    .order(created_at: :desc).page(params[:order_page]).per(5)
  end

  def load_deliveries
    @purchase_deliveries = PurchaseDelivery.ransack(params[:q]).result(distinct: true)
                                           .order(created_at: :desc).page(params[:delivery_page]).per(5)
  end
end

app/views/home/_products_partial.html.erb
<div class="col-lg-12 col-xl-7">
  <div class="card mb-30">
    <div class="card-body">
      <div class="card-header">
        <a href="<%= products_path %>" class="btn btn-primary float-right">View all</a>
        <h5 class="card-title">Products List</h5>
      </div>
      <div class="table-responsive">
        <table class="table table-hover text-vertical-middle mb-0">
          <thead class="bort-none borpt-0">
            <tr>
              <th>Product</th>
              <th>SKU</th>
              <th>Quantity</th>
              <th>Category</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td>
                  <div class="media align-items-center">
                    <% if product.photo.attached? %>
                      <%= image_tag product.photo&.service_url, class: "wh-30 mr-2", alt: "Project Image" %>
                    <% else %>
                      <%= image_tag("projects/1.jpg", alt: "Project Image", class: "wh-30 mr-2") %>
                    <% end %>
                    <strong><%= product.title %></strong>
                  </div>
                </td>
                <td><%= product.sku %></td>
                <td class="text-center"><%= product.total_stock.to_i %></td>
                <td>
                  <span class="badge badge-cyan"><%= product.category&.title %></span>
                </td>
                <td>
                  <span class="badge badge-info">
                    <span class="fw-600"><a class="link_tag" href="<%= product_path(product)%>">View</a></span>
                  </span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class='float-right mt-3'>
          <%= page_entries_info @products %>
        </div>
        <div class="pagination mt-3">
          <%= paginate @products, :param_name => :product_page, theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_purchase_deliveries_partial.html.erb
<div class="col-lg-12 col-xl-6">
  <div class="card mb-30">
    <div class="card-body">
      <div class="card-header">
        <a href="<%= purchase_deliveries_path %>" class="btn btn-primary float-right">View all</a>
        <h5 class="card-title">Purchase Deliveries List</h5>
      </div>
      <div class="table-responsive">
        <div class="pagination justify-content-center">
          <%= paginate @purchase_deliveries,:param_name => :delivery_page, theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
        <table class="table table-hover text-vertical-middle mb-0">
          <thead class="bort-none borpt-0">
            <tr>
              <th>Purchase Order</th>
              <th>Supplier</th>
              <th>Total Bill</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            <% @purchase_deliveries.each do |purchase_delivery| %>
              <tr>
                <td>
                  <strong><%= purchase_delivery.purchase_order_id %></strong>
                </td>
                <td><%= purchase_delivery.purchase_order.system_user&.name %></td>
                <td class="text-center"><%= purchase_delivery.total_bill %></td>
                <td>
                  <span class="badge badge-info">
                    <span class="fw-600"><a class="link_tag" href="<%= purchase_delivery_path(purchase_delivery)%>">View</a></span>
                  </span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class='float-right mt-3'>
          <%= page_entries_info @purchase_deliveries %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_purchase_orders_partial.html.erb
<div class="col-lg-12 col-xl-6">
  <div class="card mb-30">
    <div class="card-body">
      <div class="card-header">
        <a href="<%= purchase_orders_path %>" class="btn btn-primary float-right">View all</a>
        <h5 class="card-title">Purchase Order List</h5>
      </div>
      <div class="table-responsive">
        <div class="pagination justify-content-center">
          <%= paginate @purchase_orders, :param_name => :order_page,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
        <table class="table table-hover text-vertical-middle mb-0">
          <thead class="bort-none borpt-0">
            <tr>
              <th>Supplier Name</th>
              <th>Total Bill</th>
              <th>Purchase Deliveries</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            <% @purchase_orders.each do |purchase_order| %>
              <tr>
                <td>
                  <strong><%= purchase_order.system_user.name %></strong>
                </td>
                <td><%= purchase_order.total_bill %></td>
                <td class="text-center"><%= purchase_order.purchase_deliveries&.count %></td>
                <td>
                  <span class="badge badge-info">
                    <span class="fw-600"><a class="link_tag" href="<%= purchase_order_path(purchase_order)%>">View</a></span>
                  </span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class='float-right mt-3'>
          <%= page_entries_info @purchase_orders %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_version_partial_order.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Order Dispatch</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= order_dispatches_path %>">Order Dispatch</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Logs</span>
    </li>
    <li class="ml-auto">
      <%= link_to 'View', order_dispatch_path(id: @order.id), class: 'btn btn-primary text-white' %>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="row">
  <div class="col-lg-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <h5 class="card-title">
            Logs
          </h5>
        </div>
        <div class="table-responsive">
          <table class="table table-hover text-vertical-middle mb-0">
            <thead class="bort-none borpt-0">
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Action</th>
                <th scope="col">System ID</th>
                <th scope="col">Channel order Id</th>
                <th scope="col">User</th>
              </tr>
            </thead>
            <tbody>
              <% @versions&.each_with_index do |version| %>
                <% if version.changeset.include? 'change_log' %>
                  <tr>
                    <% change_log = version.changeset["change_log"][1].split(',')%>
                    <td><%= version.created_at&.strftime('%m/%d/%Y') %></td>
                    <td><%= version.created_at&.strftime('%I:%M %p') %></td>
                    <td><%= change_log[0] %></td>
                    <td><%= change_log[1] %></td>
                    <td><%= change_log[2] %></td>
                    <td>
                      <%= change_log[3] %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/dashboard.html.erb
<div class="main-content-header">
  <h1>Dashboard</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="<%= home_path %>">Home</a>
    </li>
    <li class="breadcrumb-item active">
        <span class="active">Dashboard</span>
    </li>
  </ol>
</div>

<div class="row">
  <div class="col-lg-3 col-sm-6">
    <%= link_to products_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Products</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:products_count] %></h3>
        </div>
        <div class="avatar avatar-gold ">
         <i data-feather="shopping-bag"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-3 col-sm-6">
    <%= link_to system_users_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Suppliers</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:suppliers_count] %></h3>
        </div>
        <div class="avatar avatar-purple ">
          <i data-feather="users"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-3 col-sm-6">
    <%= link_to purchase_orders_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Purchase Orders</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:purchase_orders_count] %></h3>
        </div>
        <div class="avatar avatar-blue ">
          <i data-feather="file-text"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-3 col-sm-6">
    <%= link_to purchase_deliveries_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Purchase Deliveries</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:purchase_deliveries_count] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="file-text"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="row">
  <%= render 'products_partial' %>
  <%= render 'suppliers_partial' %>
</div>

<div class="row">
  <%= render 'purchase_orders_partial' %>
  <%= render 'purchase_deliveries_partial' %>
</div>

<!-- Team Members & Assigned tasks-->
<div class="row">
    <div class="col-lg-4">
        <div class="card mb-30">
            <div class="card-body">
                <div class="card-header">
                    <a href="#" class="btn btn-primary float-right">View all</a>
                    <h5 class="card-title">Upcoming Meeting</h5>
                </div>

                <div class="d-flex mb-20">
                    <div class="text-center">
                        <div class="avatar avatar-blue wh-50 rounded">
                            <span class="line-height-1 pt-12">
                                17 <br> <span class="fs-11">May</span>
                            </span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-1 mt-1 fs-15">Project Meeting</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>

                <div class="d-flex mb-20">
                    <div class="text-center">
                        <div class="avatar avatar-cyan wh-50 rounded">
                            <span class="line-height-1 pt-12">
                                20 <br> <span class="fs-11">May</span>
                            </span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-1 mt-1 fs-15">Designer Discussion</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>

                <div class="d-flex mb-20">
                    <div class="text-center">
                        <div class="avatar avatar-gold wh-50 rounded">
                            <span class="line-height-1 pt-12">
                                22 <br> <span class="fs-11">May</span>
                            </span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-1 mt-1 fs-15">Development Discussion</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>

                <div class="d-flex">
                    <div class="text-center">
                        <div class="avatar avatar-red wh-50 rounded">
                            <span class="line-height-1 pt-12">
                                25 <br> <span class="fs-11">May</span>
                            </span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-0 mt-2 fs-15">Development Plan Discussion</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card mb-30">
            <div class="card-body">
                <div class="card-header">
                    <a href="#" class="btn btn-primary float-right">View all</a>
                    <h5 class="card-title">Activity</h5>
                </div>

                <div class="height-265">
                    <div class="timeline">
                        <div class="timeline-list">
                            <i class="icofont-check timeline-icon primary-color"></i>
                            <h6 class="mb-1 fs-15">Colin Firth</h6>
                            <p>Finished the project. Lorem ipsum dolor sit amet.</p>

                            <span class="fs-13 mt-2">
                                <i class="icofont-wall-clock"></i>
                                <span class="m-l-5">9:00 AM</span>
                            </span>
                        </div>

                        <div class="timeline-list">
                            <i class="icofont-check timeline-icon primary-color"></i>
                            <h6 class="mb-1 fs-15">Michael Sheen</h6>
                            <p>Great work!. Lorem ipsum dolor sit amet.</p>

                            <span class="fs-13 mt-2">
                                <i class="icofont-wall-clock"></i>
                                <span class="m-l-5">9:10 AM</span>
                            </span>
                        </div>
                        
                        <div class="timeline-list">
                            <i class="icofont-check timeline-icon primary-color"></i>
                            <h6 class="mb-1 fs-15">Tom Hardy</h6>
                            <p>Hello Jems, Lorem ipsum dolor sit amet.</p>

                            <span class="fs-13 mt-2">
                                <i class="icofont-wall-clock"></i>
                                <span class="m-l-5">9:30 AM</span>
                            </span>
                        </div>

                        <div class="timeline-list">
                            <i class="icofont-check timeline-icon primary-color"></i>
                            <h6 class="mb-1 fs-15">Daniel Craig</h6>
                            <p>Finished the project, Lorem ipsum dolor sit amet.</p>

                            <span class="fs-13 mt-2">
                                <i class="icofont-wall-clock"></i>
                                <span class="m-l-5">10:30 AM</span>
                            </span>
                        </div>

                        <div class="timeline-list">
                            <i class="icofont-check timeline-icon primary-color"></i>
                            <h6 class="mb-1 fs-15">Michael Sheen</h6>
                            <p>Great work!. Lorem ipsum dolor sit amet.</p>

                            <span class="fs-13 mt-2">
                                <i class="icofont-wall-clock"></i>
                                <span class="m-l-5">9:10 AM</span>
                            </span>
                        </div>

                        <div class="timeline-list">
                            <i class="icofont-check timeline-icon primary-color"></i>
                            <h6 class="mb-1 fs-15">Colin Firth</h6>
                            <p>Finished the project. Lorem ipsum dolor sit amet.</p>

                            <span class="fs-13 mt-2">
                                <i class="icofont-wall-clock"></i>
                                <span class="m-l-5">9:00 AM</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card mb-30">
            <div class="card-body">
                <div class="card-header">
                    <a href="#" class="btn btn-primary float-right">View all</a>
                    <h5 class="card-title">Project issues</h5>
                </div>

                <div class="d-flex mb-20">
                    <div class="text-center">
                        <div class="avatar avatar-blue wh-50 rounded">
                            <span class="fw-600 pt-3">20</span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-1 mt-1 fs-15">Errors</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>

                <div class="d-flex mb-20">
                    <div class="text-center">
                        <div class="avatar avatar-cyan wh-50 rounded">
                            <span class="fw-600 pt-3">25</span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-1 mt-1 fs-15">Design Issue</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>

                <div class="d-flex mb-20">
                    <div class="text-center">
                      <div class="avatar avatar-gold wh-50 rounded">
                        <span class="fw-600 pt-3">5</span>
                      </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-1 mt-1 fs-15">Development Issue</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>

                <div class="d-flex">
                    <div class="text-center">
                        <div class="avatar avatar-red wh-50 rounded">
                            <span class="fw-600 pt-3">25</span>
                        </div>
                    </div>

                    <div class="ml-3">
                        <h6 class="mb-0 mt-2 fs-15">Coding Issue</h6>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<h1 class="d-none"> Users </h1>