config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :services do
    collection do
      post 'import', to: 'services#import'
      get 'version', to: 'services#version'
      post 'bulk_method', to: 'services#bulk_method'
      get 'archive', to: 'services#archive'
      post 'restore', to: 'services#restore'
      post 'permanent_delete', to: 'services#permanent_delete'
      post 'season_by_name', to: 'services#search_season_by_name'
    end
  end
  resources :couriers do
    collection do
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
      post 'season_by_name', to: 'couriers#search_season_by_name'
    end
  end
  resources :import_mappings
  resources :product_locations
  resources :export_mappings do
    collection do
      get 'export_new', to: 'export_mappings#export_new'
      post 'export_create', to: 'export_mappings#export_create'
    end
  end
  resources :assign_rules
  resources :trackings do
    collection do
      post 'import', to: 'trackings#import'
      post 'auto_dispatch', to: 'trackings#auto_dispatch'
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :email_templates
  resources :general_settings do
  collection do
    post 'import', to: 'general_settings#import'
    get 'version', to: 'general_settings#version'
    post 'bulk_method', to: 'general_settings#bulk_method'
    get 'archive', to: 'general_settings#archive'
    post 'restore', to: 'general_settings#restore'
    post 'permanent_delete', to: 'general_settings#permanent_delete'
  end
end
  resources :mail_service_rules do
    collection do
      post 'import', to: 'mail_service_rules#import'
      get 'version', to: 'mail_service_rules#version'
      post 'bulk_method', to: 'mail_service_rules#bulk_method'
      get 'archive', to: 'mail_service_rules#archive'
      post 'restore', to: 'mail_service_rules#restore'
      post 'permanent_delete', to: 'mail_service_rules#permanent_delete'
      get 'search_courier_services', to: 'mail_service_rules#courier_servies'
    end
  end
  resources :seasons do
    collection do
      post 'import', to: 'seasons#import'
      post 'bulk_method', to: 'seasons#bulk_method'
      get 'archive', to: 'seasons#archive'
      post 'restore', to: 'seasons#restore'
      post 'permanent_delete', to: 'seasons#permanent_delete'
      post 'season_by_name', to: 'seasons#search_season_by_name'
    end
  end
  devise_for :users
  resources :users, except: [:create] do
    collection do
      post 'user_create', to: 'users#create'
      post 'import', to: 'users#import'
      post 'bulk_method', to: 'users#bulk_method'
      get 'archive', to: 'users#archive'
      post 'restore', to: 'users#restore'
    end
  end

  resources :products do
    collection do
      get 'version', to: 'products#version'
      post 'import', to: 'products#import'
      post 'bulk_method', to: 'products#bulk_method'
      get 'archive', to: 'products#archive'
      post 'restore', to: 'products#restore'
      post 'permanent_delete', to: 'products#permanent_delete'
      post 'products_by_title', to: 'products#search_products_by_title'
      post 'search_multipack', to: 'products#search_multipack'
      post 'products_by_sku', to: 'products#search_products_by_sku'
      post 'check_category', to: 'products#search_category'
      get 'export', to: 'products#export_logs'
    end
  end

  resources :categories do
    collection do
      post 'import', to: 'categories#import'
      get 'version', to: 'categories#version'
      post 'bulk_method', to: 'categories#bulk_method'
      get 'archive', to: 'categories#archive'
      post 'restore', to: 'categories#restore'
      post 'permanent_delete', to: 'categories#permanent_delete'
      post 'category_by_title', to: 'categories#search_category_by_title'
    end
  end

  resources :purchase_orders do
    collection do
      post 'import', to: 'purchase_orders#import'
      post 'bulk_method', to: 'purchase_orders#bulk_method'
      get 'archive', to: 'purchase_orders#archive'
      post 'restore', to: 'purchase_orders#restore'
      post 'send_email', to: 'purchase_orders#send_mail_to_supplier'
      post 'add_product', to: 'purchase_orders#add_product'
    end
    member do
      get 'quick_edit', to: 'purchase_orders#quick_edit'
    end
  end

  resources :purchase_deliveries do
    collection do
      post 'import', to: 'purchase_deliveries#import'
      post 'bulk_method', to: 'purchase_deliveries#bulk_method'
      get 'archive', to: 'purchase_deliveries#archive'
      post 'restore', to: 'purchase_deliveries#restore'
      post 'permanent_delete', to: 'purchase_deliveries#permanent_delete'
    end
  end

  resources :system_users do
    collection do
      post 'import', to: 'system_users#import'
      get 'version', to: 'system_users#version'
      post 'bulk_method', to: 'system_users#bulk_method'
      get 'archive', to: 'system_users#archive'
      post 'restore', to: 'system_users#restore'
      post 'system_user_by_name', to: 'system_users#search_system_user_by_name'
      post 'import_supplier_products', to: 'system_users#import_supplier_products'
    end
  end

  get '/home', to: 'home#dashboard'
  get '/settings', to: 'settings#index'

  resources :product_mappings do
    collection do
      post 'import', to: 'product_mappings#import'
      get 'version', to: 'product_mappings#version'
    end
  end
  resources :extra_field_names
  resources :order_dispatches do
    collection do
      get 'version', to: 'order_dispatches#version'
      post 'import', to: 'order_dispatches#import'
      get 'bulk_method', to: 'order_dispatches#bulk_method'
      post 'assign_rule', to: 'order_dispatches#assign_rule'
      get 'bulk_assign_rule', to: 'order_dispatches#bulk_assign_rule'
      get 'update_selected', to: 'order_dispatches#update_selected'
      get 'bulk_update_selected', to: 'order_dispatches#bulk_update_selected'
      get 'refresh', to: 'order_dispatches#refresh'
      get 'refresh_product', to: 'order_dispatches#refresh_product'
      get 'allocations', to: 'order_dispatches#allocations'
      post 'import_customer', to: 'order_dispatches#import_customer'
      get 'recalculate_rule', to: 'order_dispatches#recalculate_rule'
      get 'invoice', to: 'order_dispatches#invoice'
      get 'cancel_order', to: 'order_dispatches#cancel_order'
    end
  end

  resources :customers do
    collection do
      get 'version', to: 'customers#version'
      post 'add_flagging', to: 'customers#flagging_date'
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
    end
  end

  resources :pick_and_packs do
    collection do
      post 'import', to: 'pick_and_packs#import'
      post 'bulk_method', to: 'pick_and_packs#bulk_method'
      post 'assign_user', to: 'pick_and_packs#assign_user'
      get 'show_order', to: 'pick_and_packs#show_order'
      get 'start_packing', to: 'pick_and_packs#start_packing'
      post 'courier_edit', to: 'pick_and_packs#courier_edit'
      post 'address_edit', to: 'pick_and_packs#address_edit'
      get 'archive', to: 'pick_and_packs#archive'
      post 'restore', to: 'pick_and_packs#restore'
      post 'permanent_delete', to: 'pick_and_packs#permanent_delete'
      post 'season_by_name', to: 'pick_and_packs#search_season_by_name'
      get 'pick_all_items', to: 'pick_and_packs#pick_all_items'
      get 'scan_barcode', to: 'pick_and_packs#scan_barcode'
      get 'print_packing_list', to: 'pick_and_packs#print_packing_list'
      get 'download_pdf', to: 'pick_and_packs#download_pdf'
      get 'consignement', to: 'pick_and_packs#consignement'
    end
  end

  resources :order_batches do
    collection do
      get 'save_batch_name', to: 'order_batches#save_batch_name'
      post 'search_batch', to: 'order_batches#search_batch'
      get 'set_pick_preset', to: 'order_batches#set_pick_preset'
    end
  end

  resources :channel_forecastings do
    collection do
      get 'buffer_rule', to: 'channel_forecastings#buffer_rule'
      post 'assign_buffer_rule', to: 'channel_forecastings#assign_buffer_rule'
    end
  end

  resources :sellings do
    collection do
      get 'ebay_selling', to: 'sellings#ebay_selling'
    end
  end

  resources :mails
  resources :notes
  resources :inventory_reports do
    collection do
      get 'date_picker_from_to', to: 'inventory_reports#date_picker_from_to'
    end
  end

  resources :rules
  resources :job_statuses
  resources :transaction_reports do
    collection do
      get 'date_picker_from_to', to: 'transaction_reports#date_picker_from_to'
    end
  end

  resources :dispatch_reports do
    collection do
      get 'date_picker_from_to', to: 'dispatch_reports#date_picker_from_to'
    end
  end

  post 'product_file', to: 'products#import_product_file'
  post 'channel_product_file', to: 'product_mappings#import_product_file'
  post 'order_file', to: 'order_dispatches#import_order_file'
  post 'multi_file', to: 'import_mappings#multi_file_mapping'
  post 'courier_csv_export', to: 'import_mappings#courier_csv_export'
  post 'tracking_file', to: 'import_mappings#tracking_file'
  post 'consolidation_tool', to: 'import_mappings#consolidation_tool'
  get 'consolidation_tool_index', to: 'import_mappings#consolidation_tool_index'
  post 'competitive_price', to: 'import_mappings#competitive_price'
  get 'export_new_consolidation', to: 'import_mappings#export_new_consolidation'
  post 'export_new_consolidation', to: 'import_mappings#export_consolidation'
  post 'consolidation_mapping', to: 'import_mappings#consolidation_mapping'
  get 'download', to: 'import_mappings#download'

app/views/pick_and_packs/archive.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Packing Station</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="<%= pick_and_packs_path %>">Packing Station</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Archive</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->

<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <div class='mr-1 float-right'>
            <%= link_to 'Packing Station', pick_and_packs_path, class: 'btn btn-outline-info' %>
          </div>
          <h5 class="card-title"> Data</h5>
        </div>
        <%= search_form_for @q, url: archive_pick_and_packs_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>
              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#archive-modal'>Restore</a>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#delete-modal'>Permanent Delete</a>
              </div>
            </div>
            <div class="col-md-2"><br>
              <%= f.search_field :batch_name_cont, class:"form-control", placeholder:"Search in Name" %>
            </div>
            <div class='col-1 offset-8'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([10, 50, 100, 500, 1000], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div>
        <% end %>
        <br>
        <%= form_with url: restore_pick_and_packs_path , method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <tr>
                <th>
                  <div class='row' style='max-width: 65px'>
                    <div class='col-6 p-0  mt-1'>
                      <input type="checkbox" id="" name="" value="" class='col-6 select-all-checkbox'>
                    </div>
                  </div>
                </th>
                <th class="text-center">Name</th>
                <th class="text-center">Status</th>
                <th class="text-center">Packer</th>
                <th colspan="3" class="text-center">Actions</th>
              </tr>
              <% @packers&.each&.with_index(1) do |packer, index| %>
                <tr class=''>
                  <td><%= f.check_box 'object_ids[]', {}, packer.id %></td>
                  <td class="text-center"><%= packer.batch_name %></td>
                  <td class="text-center">Status</td>
                  <td class="text-center"><%= packer&.user&.personal_detail&.full_name %></td>
                  <td class="text-center">
                    <div class="dropdown dropleft">
                      <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class='lni lni-more-alt'></i>
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <%= link_to 'Restore', restore_pick_and_packs_path(object_id: packer), method: :post, data: {confirm: "Are you sure you want to restore"}, class: "dropdown-item"%>
                        <%= link_to 'Permanent Delete', permanent_delete_pick_and_packs_path(object_id: packer), method: :post, data: {confirm: "Are you sure you want to parmanent delete"}, class: "dropdown-item"%>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </table>
            <%= f.submit 'Restore', class: 'bulk-method-delete-objects d-none'%>
            <%= f.submit 'Delete', class: 'bulk-method-destroy-objects d-none'%>
          </div>
        <% end %>
        <br>
        <div class='float-right'>
          <%= page_entries_info @packers %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @packers,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="archive-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want restore selected packers?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger bulk-delete-objects">Confirm</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want permanent delete selected packers?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger bulk-destroy-objects">Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/pick_and_packs/download_pdf.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Start Packing</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Download File</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->

<div class="col-lg-12">
  <div class="card text-center mb-30">
    <table class="table m-0 table-hover">
      <thead>
        <tr>
          <th class='border-right'>File Name</th>
          <th class='border-right'>Download</th>
        </tr>
      </thead>
      <tbody>
        <% @files.each do |file| %>
          <tr>
            <% if file.include?('consignment')%>
              <% filename = file&.split('/')&.last %>
              <td><%= filename %></td>
              <td class='border-right'>
                <%= link_to "Download", download_pdf_pick_and_packs_path(download: true, url: file), download: '', class: "btn btn-primary text-white" %>
                <%= link_to "Delete", download_pdf_pick_and_packs_path(download: false, url: file), class: "btn btn-danger text-white", data: {confirm: "Are you sure?"} %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/pick_and_packs/edit.html.erb
<h1>Editing Packer</h1>

<%= render 'form', packer: @packer %>

<%= link_to 'View', @packer %> |
<%= link_to 'Back', packers_path %>

app/views/pick_and_packs/index.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Packing Station</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Packing Station</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="alert alert-dismissible fade show text-white jquery-selected-alert d-none " style="position: fixed; width:93%; z-index:99999;" role="alert"></div>
<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header d-flex">
          <h5 class="card-title"> Data</h5>
          <div class='mr-1 float-right ml-auto'>
            <%# link_to 'PDF', pick_and_packs_path(format: :pdf), class:"btn btn-outline-success", type:"button"%>
            <%= link_to 'Archives', archive_pick_and_packs_path, class: 'btn btn-outline-info' %>
          </div>
        </div>
        <%= search_form_for @q, url: pick_and_packs_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>

              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#archive-modal'>Archive</a>
              </div>
            </div>
            <div class="col-md-3"><br>
              <div class="dropdown form-group">
                <%= f.search_field :batch_name_cont, class: 'form-control dropdown-toggle', placeholder:"Search in name" %>
              </div>
            </div>
            <div class='col-1 offset-7'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([10, 50, 100, 500, 1000], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div>
        <% end %>
        <br>
        <%= form_with url: bulk_method_pick_and_packs_path , method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <tr>
                <th>
                  <div class='row pl-3'>
                    <div class='col-6 p-0 mt-1'>
                      <input type="checkbox" id="" name="" value="" class='col-6 select-all-checkbox'>
                    </div>
                  </div>
                </th>
                <th class="text-center">Name</th>
                <th class="text-center">Status</th>
                <th class="text-center">Packer</th>
                <th colspan="3" class="text-center">Actions</th>
              </tr>
              <% @pick_and_packs&.each&.with_index(1) do |pick_and_pack, index| %>
                <tr class='<%= pick_and_pack.channel_orders.count > 0 ? '' : 'alert-danger' %>'>
                  <td>
                    <div class='row pl-3'>
                      <div class='col-6 p-0 mt-1'>
                        <%= f.check_box 'object_ids[]', {}, pick_and_pack.id %>
                      </div>
                    </div>
                  </td>
                  <td class="text-center"><%= pick_and_pack.batch_name %></td>
                  <td class="text-center"><%= pick_and_pack&.status %></td>
                  <td class="text-center"><%= pick_and_pack&.user&.personal_detail&.full_name %></td>
                  <td class="text-center">
                    <div class="dropdown dropleft">
                      <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Actions">
                        <i class='lni lni-more-alt'></i>
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <%= link_to 'Orders', pick_and_pack_path(pick_and_pack), class: 'dropdown-item', remote: true %>
                        <a class="trigger_orders_modal_<%= pick_and_pack.id %> d-none" data-toggle="modal" data-target='#orders-modal'>Orders</a>
                        <%#= link_to 'Start Packing', show_order_pick_and_packs_path(id: pick_and_pack.channel_orders&.first&.id), class: 'dropdown-item' %>
                        <a class="dropdown-item assign_user" data-id="<%= pick_and_pack.id %>">Assign Packer</a>
                        <% if pick_and_pack.channel_orders.count == 0 %>
                          <%= link_to 'Archive', pick_and_pack_path(pick_and_pack), method: 'delete', data: {confirm: "Are you sure you want to archive"}, class: "dropdown-item"%>
                        <% end %>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
              <%= f.submit '', class: 'bulk-method-delete-objects d-none'%>
            </table>
          </div>
        <% end %>
        <br>
        <div class='float-right'>
          <%= page_entries_info @pick_and_packs %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @pick_and_packs,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class='show_orders'></div>

<div class="modal" id="packer-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Assign Packer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: assign_user_pick_and_packs_path, method: :post do |f| %>
        <div class="modal-body">
          <%= hidden_field_tag :batch_id %>
          <label>Please select packer</label>
          <%= f.select :user_id, options_for_select(@user_list&.collect { | user | [user&.personal_detail&.full_name, user&.id] }, @user&.id), {}, class: 'form-control' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= f.submit 'Assign', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pick_and_packs/show_order.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Packing Station</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="<%= pick_and_packs_path %>">Packing Station</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">View</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->

<%= render "information_show", batch_order: @batch_order %>

app/views/pick_and_packs/start_packing.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Start Packing</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Start Packing</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="alert alert-dismissible fade show text-white jquery-selected-alert d-none " style="position: fixed; width:93%; z-index:99999;" role="alert"></div>
<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="d-flex mb-2">
          <% if params[:q].try(:[], :batch_name_eq).present? %>
            <%= link_to "Print Packing List", print_packing_list_pick_and_packs_path(batch_name: params[:q].try(:[], :batch_name_eq)) , id: "print_packing_list_id", class: "btn btn-primary float-right ml-auto"%>
          <% end %>
          <% class_set = params[:q].try(:[], :batch_name_eq).present? ? ' ' : 'ml-auto'%>
          <%= search_form_for @q, url: start_packing_pick_and_packs_path, method: :get, class: class_set  do |f| %>
            <%= f.select :batch_name_eq, options_for_select(@batches.collect { | batch | [batch.batch_name.titleize, batch.batch_name] }, f.object.batch_name_eq),{include_blank: 'Please select batch'}, class: 'form-control ml-3 batches-select' %>
            <%= f.submit 'check', class: 'batches-button-submit d-none'%>
          <% end %>
        </div>
        <div class="row">
          <div class="col-12 border-top-0 border-bottom-0 border-left-0">
          </div>
          <div class="col-12">
          <% if @tracking_order&.present? %>
            <%= form_tag(scan_barcode_pick_and_packs_path(), method: :get) do |f| %>
              <%= hidden_field_tag :"q[batch_name_eq]", params[:q].try(:[], :batch_name_eq) %>
              <%= hidden_field_tag :tracking_no, params[:tracking_no] %>
              <div class="row">
                <%= label_tag :query, "Scan barcode:", class: 'col-3 mx-auto' %>
              </div>
              <div class="form-group row">
                <%= text_field_tag :barcode,{}, autofocus: true, required: true, class: 'form-control col-3 mx-auto', placeholder: 'Please scan barcode' %>
              </div>
              <%= submit_tag 'check', class: 'd-none'%>
            <% end %>
            <%= render "information_show", batch_order: @tracking_order %>
          <% else %>
            <%= form_tag(start_packing_pick_and_packs_path(), method: :get) do |f| %>
              <%= hidden_field_tag :"q[batch_name_eq]", params[:q].try(:[], :batch_name_eq) %>
              <div class="row">
                <%= label_tag :query, "Enter or scan tracking:", class: 'col-3 mx-auto' %>
              </div>
              <div class="form-group row">
                <%= text_field_tag :tracking_no, {}, autofocus: true, required: true, class: 'form-control col-3 mx-auto', placeholder: 'Please scan or enter tracking' %>
              </div>
              <%= submit_tag 'check', class: 'd-none'%>
            <% end %>
            <table class="table m-0 table-hover">
              <tr>
                <th class="text-center">Name</th>
                <th class="text-center">Order No.</th>
                <th class="text-center">Tracking No.</th>
                <th class="text-center">Items</th>
              </tr>
              <% @orders&.each do |order|%>
                <tr>
                  <td class="text-center"><%= order.buyer_name%></td>
                  <td class="text-center"><%= order.order_id%></td>
                  <td class="text-center">
                    <% order.trackings&.each do |item| %>
                      <%= item.tracking_no %><br>
                    <% end %>
                  </td>
                  <td class="text-center"><%= order.channel_order_items&.count%></td>
                </tr>
              <% end %>
            </table>
          <% end %>
          </div>
        <div>
        <div class='float-right'>
          <%# page_entries_info @pick_and_packs %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%# paginate @pick_and_packs,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>