config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :services do
    collection do
      post 'import', to: 'services#import'
      get 'version', to: 'services#version'
      post 'bulk_method', to: 'services#bulk_method'
      get 'archive', to: 'services#archive'
      post 'restore', to: 'services#restore'
      post 'permanent_delete', to: 'services#permanent_delete'
      post 'season_by_name', to: 'services#search_season_by_name'
    end
  end
  resources :couriers do
    collection do
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
      post 'season_by_name', to: 'couriers#search_season_by_name'
    end
  end
  resources :import_mappings
  resources :product_locations
  resources :export_mappings do
    collection do
      get 'export_new', to: 'export_mappings#export_new'
      post 'export_create', to: 'export_mappings#export_create'
    end
  end
  resources :assign_rules
  resources :trackings do
    collection do
      post 'import', to: 'trackings#import'
      post 'auto_dispatch', to: 'trackings#auto_dispatch'
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :email_templates
  resources :general_settings do
  collection do
    post 'import', to: 'general_settings#import'
    get 'version', to: 'general_settings#version'
    post 'bulk_method', to: 'general_settings#bulk_method'
    get 'archive', to: 'general_settings#archive'
    post 'restore', to: 'general_settings#restore'
    post 'permanent_delete', to: 'general_settings#permanent_delete'
  end
end
  resources :mail_service_rules do
    collection do
      post 'import', to: 'mail_service_rules#import'
      get 'version', to: 'mail_service_rules#version'
      post 'bulk_method', to: 'mail_service_rules#bulk_method'
      get 'archive', to: 'mail_service_rules#archive'
      post 'restore', to: 'mail_service_rules#restore'
      post 'permanent_delete', to: 'mail_service_rules#permanent_delete'
      get 'search_courier_services', to: 'mail_service_rules#courier_servies'
    end
  end
  resources :seasons do
    collection do
      post 'import', to: 'seasons#import'
      post 'bulk_method', to: 'seasons#bulk_method'
      get 'archive', to: 'seasons#archive'
      post 'restore', to: 'seasons#restore'
      post 'permanent_delete', to: 'seasons#permanent_delete'
      post 'season_by_name', to: 'seasons#search_season_by_name'
    end
  end
  devise_for :users
  resources :users, except: [:create] do
    collection do
      post 'user_create', to: 'users#create'
      post 'import', to: 'users#import'
      post 'bulk_method', to: 'users#bulk_method'
      get 'archive', to: 'users#archive'
      post 'restore', to: 'users#restore'
    end
  end

  resources :products do
    collection do
      get 'version', to: 'products#version'
      post 'import', to: 'products#import'
      post 'bulk_method', to: 'products#bulk_method'
      get 'archive', to: 'products#archive'
      post 'restore', to: 'products#restore'
      post 'permanent_delete', to: 'products#permanent_delete'
      post 'products_by_title', to: 'products#search_products_by_title'
      post 'search_multipack', to: 'products#search_multipack'
      post 'products_by_sku', to: 'products#search_products_by_sku'
      post 'check_category', to: 'products#search_category'
      get 'export', to: 'products#export_logs'
    end
  end

  resources :categories do
    collection do
      post 'import', to: 'categories#import'
      get 'version', to: 'categories#version'
      post 'bulk_method', to: 'categories#bulk_method'
      get 'archive', to: 'categories#archive'
      post 'restore', to: 'categories#restore'
      post 'permanent_delete', to: 'categories#permanent_delete'
      post 'category_by_title', to: 'categories#search_category_by_title'
    end
  end

  resources :purchase_orders do
    collection do
      post 'import', to: 'purchase_orders#import'
      post 'bulk_method', to: 'purchase_orders#bulk_method'
      get 'archive', to: 'purchase_orders#archive'
      post 'restore', to: 'purchase_orders#restore'
      post 'send_email', to: 'purchase_orders#send_mail_to_supplier'
      post 'add_product', to: 'purchase_orders#add_product'
    end
    member do
      get 'quick_edit', to: 'purchase_orders#quick_edit'
    end
  end

  resources :purchase_deliveries do
    collection do
      post 'import', to: 'purchase_deliveries#import'
      post 'bulk_method', to: 'purchase_deliveries#bulk_method'
      get 'archive', to: 'purchase_deliveries#archive'
      post 'restore', to: 'purchase_deliveries#restore'
      post 'permanent_delete', to: 'purchase_deliveries#permanent_delete'
    end
  end

  resources :system_users do
    collection do
      post 'import', to: 'system_users#import'
      get 'version', to: 'system_users#version'
      post 'bulk_method', to: 'system_users#bulk_method'
      get 'archive', to: 'system_users#archive'
      post 'restore', to: 'system_users#restore'
      post 'system_user_by_name', to: 'system_users#search_system_user_by_name'
      post 'import_supplier_products', to: 'system_users#import_supplier_products'
    end
  end

  get '/home', to: 'home#dashboard'
  get '/settings', to: 'settings#index'

  resources :product_mappings do
    collection do
      post 'import', to: 'product_mappings#import'
      get 'version', to: 'product_mappings#version'
    end
  end
  resources :extra_field_names
  resources :order_dispatches do
    collection do
      get 'version', to: 'order_dispatches#version'
      post 'import', to: 'order_dispatches#import'
      get 'bulk_method', to: 'order_dispatches#bulk_method'
      post 'assign_rule', to: 'order_dispatches#assign_rule'
      get 'bulk_assign_rule', to: 'order_dispatches#bulk_assign_rule'
      get 'update_selected', to: 'order_dispatches#update_selected'
      get 'bulk_update_selected', to: 'order_dispatches#bulk_update_selected'
      get 'refresh', to: 'order_dispatches#refresh'
      get 'refresh_product', to: 'order_dispatches#refresh_product'
      get 'allocations', to: 'order_dispatches#allocations'
      post 'import_customer', to: 'order_dispatches#import_customer'
      get 'recalculate_rule', to: 'order_dispatches#recalculate_rule'
      get 'invoice', to: 'order_dispatches#invoice'
      get 'cancel_order', to: 'order_dispatches#cancel_order'
    end
  end

  resources :customers do
    collection do
      get 'version', to: 'customers#version'
      post 'add_flagging', to: 'customers#flagging_date'
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
    end
  end

  resources :pick_and_packs do
    collection do
      post 'import', to: 'pick_and_packs#import'
      post 'bulk_method', to: 'pick_and_packs#bulk_method'
      post 'assign_user', to: 'pick_and_packs#assign_user'
      get 'show_order', to: 'pick_and_packs#show_order'
      get 'start_packing', to: 'pick_and_packs#start_packing'
      post 'courier_edit', to: 'pick_and_packs#courier_edit'
      post 'address_edit', to: 'pick_and_packs#address_edit'
      get 'archive', to: 'pick_and_packs#archive'
      post 'restore', to: 'pick_and_packs#restore'
      post 'permanent_delete', to: 'pick_and_packs#permanent_delete'
      post 'season_by_name', to: 'pick_and_packs#search_season_by_name'
      get 'pick_all_items', to: 'pick_and_packs#pick_all_items'
      get 'scan_barcode', to: 'pick_and_packs#scan_barcode'
      get 'print_packing_list', to: 'pick_and_packs#print_packing_list'
      get 'download_pdf', to: 'pick_and_packs#download_pdf'
      get 'consignement', to: 'pick_and_packs#consignement'
    end
  end

  resources :order_batches do
    collection do
      get 'save_batch_name', to: 'order_batches#save_batch_name'
      post 'search_batch', to: 'order_batches#search_batch'
      get 'set_pick_preset', to: 'order_batches#set_pick_preset'
    end
  end

  resources :channel_forecastings do
    collection do
      get 'buffer_rule', to: 'channel_forecastings#buffer_rule'
      post 'assign_buffer_rule', to: 'channel_forecastings#assign_buffer_rule'
    end
  end

  resources :sellings do
    collection do
      get 'ebay_selling', to: 'sellings#ebay_selling'
    end
  end

  resources :mails
  resources :notes
  resources :inventory_reports do
    collection do
      get 'date_picker_from_to', to: 'inventory_reports#date_picker_from_to'
    end
  end

  resources :rules
  resources :job_statuses
  resources :transaction_reports do
    collection do
      get 'date_picker_from_to', to: 'transaction_reports#date_picker_from_to'
    end
  end

  resources :dispatch_reports do
    collection do
      get 'date_picker_from_to', to: 'dispatch_reports#date_picker_from_to'
    end
  end

  post 'product_file', to: 'products#import_product_file'
  post 'channel_product_file', to: 'product_mappings#import_product_file'
  post 'order_file', to: 'order_dispatches#import_order_file'
  post 'multi_file', to: 'import_mappings#multi_file_mapping'
  post 'courier_csv_export', to: 'import_mappings#courier_csv_export'
  post 'tracking_file', to: 'import_mappings#tracking_file'
  post 'consolidation_tool', to: 'import_mappings#consolidation_tool'
  get 'consolidation_tool_index', to: 'import_mappings#consolidation_tool_index'
  post 'competitive_price', to: 'import_mappings#competitive_price'
  get 'export_new_consolidation', to: 'import_mappings#export_new_consolidation'
  post 'export_new_consolidation', to: 'import_mappings#export_consolidation'
  post 'consolidation_mapping', to: 'import_mappings#consolidation_mapping'
  get 'download', to: 'import_mappings#download'

app/models/purchase_delivery.rb
# frozen_string_literal: true

# single delivery may be many delivery details
class PurchaseDelivery < ApplicationRecord
  acts_as_paranoid

  belongs_to :purchase_order
  has_many :purchase_delivery_details, dependent: :destroy

  accepts_nested_attributes_for :purchase_delivery_details, allow_destroy: true

  def self.to_csv
    attributes = all.column_names
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |purchase_delivery|
        csv << attributes.map { |attr| purchase_delivery.send(attr) }
      end
    end
  end
end

app/controllers/purchase_deliveries_controller.rb
# frozen_string_literal: true

# PurchaseDeliveries Crud
class PurchaseDeliveriesController < ApplicationController
  include ImportExport

  before_action :authenticate_user!
  before_action :find_purchase_delivery, only: %i[show edit update destroy]
  after_action :restore_childs, only: :restore
  before_action :filter_object_ids, only: %i[bulk_method restore]
  before_action :klass_bulk_method, only: %i[bulk_method]
  before_action :klass_restore, only: %i[restore]
  before_action :klass_import, only: %i[import]

  def index
    @q = PurchaseDelivery.ransack(params[:q])
    @purchase_deliveries = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(params[:limit])
    export_csv(@purchase_deliveries) if params[:export_csv].present?
  end

  def new
    @purchase_order = PurchaseOrder.find(params[:purchase_order_id])
    if @purchase_order.order_status == 'completed'
      flash[:notice] = 'Order Delivery is already completed.'
      redirect_to purchase_order_path(@purchase_order)
    elsif @purchase_order.purchase_order_details.map {|p| p.quantity.to_i.zero? ? '' : p.product.product_type}.any? nil
      flash[:notice] = 'Please create temporary products first.'
      redirect_to purchase_order_path(@purchase_order)
    else
      @purchase_order_details = @purchase_order.purchase_order_details
      @purchase_delivery = PurchaseDelivery.new
      @purchase_delivery.purchase_delivery_details.build
    end
  end

  def create
    @purchase_delivery = PurchaseDelivery.new(purchase_delivery_params)
    if @purchase_delivery.save
      id = @purchase_delivery.purchase_order_id
      PurchaseOrder.find(id).update(order_status: params[:order_status])
      flash[:notice] = 'Order Delivered Successfully.'
      redirect_to purchase_order_path(id)
    else
      flash.now[:notice] = 'Not Succesfully Delivered.'
      render 'new'
    end
  end

  def show
    @supplier = PurchaseOrder.find(@purchase_delivery.purchase_order_id).supplier_id
  end

  def edit; end

  def update
    if @purchase_delivery.purchase_order.order_status == 'completed'
      flash[:notice] = 'Order Delivery is already completed.'
      redirect_to purchase_delivery_path(@purchase_delivery)
    elsif @purchase_delivery.update(purchase_delivery_params)
      @purchase_delivery.purchase_order.update(order_status: params[:order_status])
      flash[:notice] = 'Order Delivery updated successfully.'
      redirect_to purchase_delivery_path(@purchase_delivery)
    else
      flash.now[:notice] = 'Order Delivery not updated.'
      render 'show'
    end
  end

  def destroy
    if @purchase_delivery.destroy
      flash[:notice] = 'Purchase Delivery archive successfully.'
      redirect_to purchase_deliveries_path
    else
      flash.now[:notice] = 'Purchase Delivery not archived.'
      render purchase_deliveries_path
    end
  end

  def export_csv(purchase_deliveries)
    request.format = 'csv'
    respond_to do |format|
      format.csv { send_data purchase_deliveries.to_csv, filename: "purchase-deliveries-#{Date.today}.csv" }
    end
  end

  def import
    if @csv.present?
      csv_create_records(@csv)
      flash[:notice] = 'File Upload Successful!'
    end
    redirect_to purchase_deliveries_path
  end

  def bulk_method
    redirect_to purchase_deliveries_path
  end

  def archive
    @q = PurchaseDelivery.only_deleted.ransack(params[:q])
    @purchase_deliveries = @q.result(distinct: true).page(params[:page]).per(params[:limit])
  end

  def restore
    redirect_to archive_purchase_deliveries_path
  end

  def permanent_delete
    if params[:object_id].present? && PurchaseDelivery.only_deleted.find(params[:object_id]).really_destroy!
      flash[:notice] = 'Purchase Delivery deleted successfully'
    else
      flash[:notice] = 'Purchase Delivery cannot be deleted/Please select something to delete'
      redirect_to archive_purchase_deliveries_path
    end
  end

  private

  def find_purchase_delivery
    @purchase_delivery = PurchaseDelivery.find(params[:id])
  end

  def restore_childs
    @purchase_deliveries = PurchaseDeliveryDetail.only_deleted.where(purchase_delivery_id: params[:object_id])
    @purchase_deliveries&.each do |detail|
      return unless detail.restore

      @product = Product.find(detail.product.id)
      @stock = @product.total_stock.to_i + detail.quantity.to_i
      @available_stock = @product.available_stock.to_i + detail.quantity.to_i
      inventory_balance = @stock - @product.unshipped.to_i
      @product.update(total_stock: @stock, available_stock: @available_stock, change_log: "Purchase Order, #{detail.id}, #{detail.purchase_order.system_user.name}, Purchase Order Recieved, #{(detail.purchase_order.purchase_order_details.last.cost_price.to_f * detail.quantity.to_i)}, #{inventory_balance}, #{detail.quantity.to_i}")
    end
  end

  def purchase_delivery_params
    params.require(:purchase_delivery).permit(
      :purchase_order_id,
      :total_bill,
      purchase_delivery_details_attributes: %i[
        id purchase_delivery_id
        product_id cost_price
        quantity missing
        deleted_at demaged
      ]
    )
  end

  def csv_create_records(csv)
    csv.each do |row|
      data = PurchaseDelivery.with_deleted.find_or_initialize_by(id: row['id'])
      if !data.update(row.to_hash)
        flash[:alert] = "#{data.errors.full_messages} at ID: #{data.id} , Try again"
      else
        data.update(user_type: 'supplier')
      end
    end
  end
end

app/views/purchase_deliveries/archive.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
    <h1>Purchase Deliveries</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="<%= home_path %>">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="<%= purchase_deliveries_path %>">Purchase Deliveries</a>
        </li>
        <li class="breadcrumb-item active">
            <span class="active">Archives</span>
        </li>
    </ol>
</div>
<!-- End Main Content Header -->

<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <div class='mr-1 float-right'>
            <%= link_to 'Purchase Deliveries', purchase_deliveries_path, class: 'btn btn-outline-info' %>
          </div>
          <h5 class="card-title"> Data</h5>
        </div>
        <%= search_form_for @q, url: purchase_deliveries_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>
              <!--
              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Archive', '#', data: {confirm: "Are you sure you want to archive"}, class:  'dropdown-item bulk-delete-objects' %>
              </div>
              -->
            </div>
            <div class='col-1 offset-10'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([10, 50, 100, 500, 1000], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div>
        <% end %>
        <br>
        <%= form_with url: bulk_method_purchase_deliveries_path , method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <tr>
                <th><input type="checkbox" id="" name="" value="" class='select-all-checkbox'></th>
                <th class="text-center">ID</th>
                <th class="text-center">Purchase Order</th>
                <th class="text-center">Total Bill</th>
                <th class="text-center">Created at</th>
                <th colspan="3" class="text-center">Actions</th>
              </tr>
              <% @purchase_deliveries&.each&.with_index(1) do |purchase_delivery, index| %>
                <tr class=''>
                  <td><%= f.check_box 'object_ids[]', {}, purchase_delivery.id %></td>
                  <td class="text-center"><%= purchase_delivery.id %></td>
                  <td class="text-center"><%= purchase_delivery.purchase_order_id %></td>
                  <td class="text-center"><%= purchase_delivery.total_bill %></td>
                  <td class="text-center"><%= purchase_delivery.created_at %></td>

                  <td class="text-center">
                    <div class="dropdown dropleft">
                      <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class='lni lni-more-alt'></i>
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <%= link_to 'Restore', restore_purchase_deliveries_path(object_id: purchase_delivery), method: :post, data: {confirm: "Are you sure you want to restore"}, class: "dropdown-item"%>
                          <%= link_to 'Permanent Delete', permanent_delete_purchase_deliveries_path(object_id: purchase_delivery), method: :post, data: {confirm: "Are you sure you want to parmanent delete"}, class: "dropdown-item"%>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
              <%= f.submit '', class: 'bulk-method-delete-objects d-none'%>
            </table>
          </div>
        <% end %>
        <br>
        <div class='float-right'>
          <%= page_entries_info @purchase_deliveries %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @purchase_deliveries,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/purchase_deliveries/index.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Purchase Deliveries</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Purchase Deliveries</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->

<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <span class='mr-1 float-right'>
            <%= form_tag import_purchase_deliveries_path, multipart: true, method: :post do %>
              <%= file_field_tag :file, class: 'd-none import-file' %>
              <button type='button' class='btn btn-outline-success import-btn'>Import</button>
              <%= submit_tag "Import", class: 'd-none import-submit' %>
            <% end %>
          </span>
          <div class='mr-1 float-right'>
            <%= link_to 'Export', purchase_deliveries_path(format: :csv, export_csv: true), class: 'btn btn-outline-primary' %>
          </div>
          <div class='mr-1 float-right'>
            <%= link_to 'Archives', archive_purchase_deliveries_path, class: 'btn btn-outline-info' %>
          </div>
          <h5 class="card-title"> Data</h5>
        </div>
        <%= search_form_for @q, url: purchase_deliveries_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>
              <!--
              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Archive', '#', data: {confirm: "Are you sure you want to archive"}, class:  'dropdown-item bulk-delete-objects' %>
              </div>
              -->
            </div>
            <div class='col-1 offset-10'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([10, 50, 100, 500, 1000], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div>
        <% end %>
        <br>
        <%= form_with url: bulk_method_purchase_deliveries_path , method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <tr>
                <th><input type="checkbox" id="" name="" value="" class='select-all-checkbox'></th>
                <th class="text-center">ID</th>
                <th class="text-center">Purchase Order</th>
                <th class="text-center">Total Bill</th>
                <th class="text-center">Created at</th>
                <th colspan="3" class="text-center">Actions</th>
              </tr>
              <% @purchase_deliveries&.each&.with_index(1) do |purchase_delivery, index| %>
                <tr class=''>
                  <td><%= f.check_box 'object_ids[]', {}, purchase_delivery.id %></td>
                  <td class="text-center"><%= purchase_delivery.id %></td>
                  <td class="text-center"><%= purchase_delivery.purchase_order_id %></td>
                  <td class="text-center"><%= purchase_delivery.total_bill %></td>
                  <td class="text-center"><%= purchase_delivery.created_at %></td>

                  <td class="text-center">
                    <div class="dropdown dropleft">
                      <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class='lni lni-more-alt'></i>
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="<%= purchase_delivery_path(purchase_delivery)%>">View</a>
                        <%= link_to 'Archive', purchase_delivery_path(purchase_delivery), method: 'delete', data: {confirm: "Are you sure you want to archive"}, class: "dropdown-item"%>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
              <%= f.submit '', class: 'bulk-method-delete-objects d-none'%>
            </table>
          </div>
        <% end %>
        <br>
        <div class='float-right'>
          <%= page_entries_info @purchase_deliveries %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @purchase_deliveries,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>