config/routes.rb
      get 'version', to: 'services#version'
      post 'bulk_method', to: 'services#bulk_method'
      get 'archive', to: 'services#archive'
      post 'restore', to: 'services#restore'
      post 'permanent_delete', to: 'services#permanent_delete'
      post 'season_by_name', to: 'services#search_season_by_name'
    end
  end
  resources :couriers do
    collection do
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
      post 'season_by_name', to: 'couriers#search_season_by_name'
    end
  end
  resources :import_mappings
  resources :product_locations
  resources :export_mappings do
    collection do
      get 'export_new', to: 'export_mappings#export_new'
      post 'export_create', to: 'export_mappings#export_create'
    end
  end
  resources :assign_rules
  resources :trackings do
    collection do
      post 'import', to: 'trackings#import'
      post 'auto_dispatch', to: 'trackings#auto_dispatch'
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :email_templates
  resources :general_settings do
  collection do
    post 'import', to: 'general_settings#import'
    get 'version', to: 'general_settings#version'
    post 'bulk_method', to: 'general_settings#bulk_method'
    get 'archive', to: 'general_settings#archive'
    post 'restore', to: 'general_settings#restore'
    post 'permanent_delete', to: 'general_settings#permanent_delete'
  end
end
  resources :mail_service_rules do
    collection do
      post 'import', to: 'mail_service_rules#import'
      get 'version', to: 'mail_service_rules#version'
      post 'bulk_method', to: 'mail_service_rules#bulk_method'
      get 'archive', to: 'mail_service_rules#archive'
      post 'restore', to: 'mail_service_rules#restore'
      post 'permanent_delete', to: 'mail_service_rules#permanent_delete'
      get 'search_courier_services', to: 'mail_service_rules#courier_servies'
    end
  end
  resources :seasons do
    collection do
      post 'import', to: 'seasons#import'
      post 'bulk_method', to: 'seasons#bulk_method'
      get 'archive', to: 'seasons#archive'
      post 'restore', to: 'seasons#restore'
      post 'permanent_delete', to: 'seasons#permanent_delete'
      post 'season_by_name', to: 'seasons#search_season_by_name'
    end
  end
  devise_for :users
  resources :users, except: [:create] do
    collection do
      post 'user_create', to: 'users#create'
      post 'import', to: 'users#import'
      post 'bulk_method', to: 'users#bulk_method'
      get 'archive', to: 'users#archive'
      post 'restore', to: 'users#restore'
    end
  end

  resources :products do
    collection do
      get 'version', to: 'products#version'
      post 'import', to: 'products#import'
      post 'bulk_method', to: 'products#bulk_method'
      get 'archive', to: 'products#archive'
      post 'restore', to: 'products#restore'
      post 'permanent_delete', to: 'products#permanent_delete'
      post 'products_by_title', to: 'products#search_products_by_title'
      post 'search_multipack', to: 'products#search_multipack'
      post 'products_by_sku', to: 'products#search_products_by_sku'
      post 'check_category', to: 'products#search_category'
      get 'export', to: 'products#export_logs'
    end
  end

  resources :categories do
    collection do
      post 'import', to: 'categories#import'
      get 'version', to: 'categories#version'
      post 'bulk_method', to: 'categories#bulk_method'
      get 'archive', to: 'categories#archive'
      post 'restore', to: 'categories#restore'
      post 'permanent_delete', to: 'categories#permanent_delete'
      post 'category_by_title', to: 'categories#search_category_by_title'
    end
  end

  resources :purchase_orders do
    collection do
      post 'import', to: 'purchase_orders#import'
      post 'bulk_method', to: 'purchase_orders#bulk_method'
      get 'archive', to: 'purchase_orders#archive'
      post 'restore', to: 'purchase_orders#restore'
      post 'send_email', to: 'purchase_orders#send_mail_to_supplier'
      post 'add_product', to: 'purchase_orders#add_product'
    end
    member do
      get 'quick_edit', to: 'purchase_orders#quick_edit'
    end
  end

  resources :purchase_deliveries do
    collection do
      post 'import', to: 'purchase_deliveries#import'
      post 'bulk_method', to: 'purchase_deliveries#bulk_method'
      get 'archive', to: 'purchase_deliveries#archive'
      post 'restore', to: 'purchase_deliveries#restore'
      post 'permanent_delete', to: 'purchase_deliveries#permanent_delete'
    end
  end

  resources :system_users do
    collection do
      post 'import', to: 'system_users#import'
      get 'version', to: 'system_users#version'
      post 'bulk_method', to: 'system_users#bulk_method'
      get 'archive', to: 'system_users#archive'
      post 'restore', to: 'system_users#restore'
      post 'system_user_by_name', to: 'system_users#search_system_user_by_name'
      post 'import_supplier_products', to: 'system_users#import_supplier_products'
    end
  end

  get '/home', to: 'home#dashboard'
  get '/settings', to: 'settings#index'

  resources :product_mappings do
    collection do
      post 'import', to: 'product_mappings#import'
      get 'version', to: 'product_mappings#version'
    end
  end
  resources :extra_field_names
  resources :order_dispatches do
    collection do
      get 'version', to: 'order_dispatches#version'
      post 'import', to: 'order_dispatches#import'
      get 'bulk_method', to: 'order_dispatches#bulk_method'
      post 'assign_rule', to: 'order_dispatches#assign_rule'
      get 'bulk_assign_rule', to: 'order_dispatches#bulk_assign_rule'
      get 'update_selected', to: 'order_dispatches#update_selected'
      get 'bulk_update_selected', to: 'order_dispatches#bulk_update_selected'
      get 'refresh', to: 'order_dispatches#refresh'
      get 'refresh_product', to: 'order_dispatches#refresh_product'
      get 'allocations', to: 'order_dispatches#allocations'
      post 'import_customer', to: 'order_dispatches#import_customer'
      get 'recalculate_rule', to: 'order_dispatches#recalculate_rule'
      get 'invoice', to: 'order_dispatches#invoice'
      get 'cancel_order', to: 'order_dispatches#cancel_order'
    end
  end

  resources :customers do
    collection do
      get 'version', to: 'customers#version'
      post 'add_flagging', to: 'customers#flagging_date'
      post 'import', to: 'couriers#import'
      post 'bulk_method', to: 'couriers#bulk_method'
      get 'archive', to: 'couriers#archive'
      post 'restore', to: 'couriers#restore'
      post 'permanent_delete', to: 'couriers#permanent_delete'
    end
  end

  resources :pick_and_packs do
    collection do
      post 'import', to: 'pick_and_packs#import'
      post 'bulk_method', to: 'pick_and_packs#bulk_method'
      post 'assign_user', to: 'pick_and_packs#assign_user'
      get 'show_order', to: 'pick_and_packs#show_order'
      get 'start_packing', to: 'pick_and_packs#start_packing'
      post 'courier_edit', to: 'pick_and_packs#courier_edit'
      post 'address_edit', to: 'pick_and_packs#address_edit'
      get 'archive', to: 'pick_and_packs#archive'
      post 'restore', to: 'pick_and_packs#restore'
      post 'permanent_delete', to: 'pick_and_packs#permanent_delete'
      post 'season_by_name', to: 'pick_and_packs#search_season_by_name'
      get 'pick_all_items', to: 'pick_and_packs#pick_all_items'
      get 'scan_barcode', to: 'pick_and_packs#scan_barcode'
      get 'print_packing_list', to: 'pick_and_packs#print_packing_list'
      get 'download_pdf', to: 'pick_and_packs#download_pdf'
      get 'consignement', to: 'pick_and_packs#consignement'
    end
  end

  resources :order_batches do
    collection do
      get 'save_batch_name', to: 'order_batches#save_batch_name'
      post 'search_batch', to: 'order_batches#search_batch'
      get 'set_pick_preset', to: 'order_batches#set_pick_preset'
    end
  end

  resources :channel_forecastings do
    collection do
      get 'buffer_rule', to: 'channel_forecastings#buffer_rule'
      post 'assign_buffer_rule', to: 'channel_forecastings#assign_buffer_rule'
    end
  end

  resources :sellings do
    collection do
      get 'ebay_selling', to: 'sellings#ebay_selling'
    end
  end

  resources :mails
  resources :notes
  resources :inventory_reports do
    collection do
      get 'date_picker_from_to', to: 'inventory_reports#date_picker_from_to'
    end
  end

  resources :rules
  resources :job_statuses
  resources :transaction_reports do
    collection do
      get 'date_picker_from_to', to: 'transaction_reports#date_picker_from_to'
    end
  end

  resources :dispatch_reports do
    collection do
      get 'date_picker_from_to', to: 'dispatch_reports#date_picker_from_to'
    end
  end

  post 'product_file', to: 'products#import_product_file'
  post 'channel_product_file', to: 'product_mappings#import_product_file'
  post 'order_file', to: 'order_dispatches#import_order_file'
  post 'multi_file', to: 'import_mappings#multi_file_mapping'
  post 'courier_csv_export', to: 'import_mappings#courier_csv_export'
  post 'tracking_file', to: 'import_mappings#tracking_file'
  post 'consolidation_tool', to: 'import_mappings#consolidation_tool'
  get 'consolidation_tool_index', to: 'import_mappings#consolidation_tool_index'
  post 'competitive_price', to: 'import_mappings#competitive_price'
  get 'export_new_consolidation', to: 'import_mappings#export_new_consolidation'
  post 'export_new_consolidation', to: 'import_mappings#export_consolidation'
  post 'consolidation_mapping', to: 'import_mappings#consolidation_mapping'
  get 'download', to: 'import_mappings#download'
  post 'auto_dispatch', to: 'import_mappings#auto_dispatch'
  get 'new_auto_dispatch', to: 'import_mappings#new_auto_dispatch'

app/models/category.rb
# frozen_string_literal: true

# differientate between products
class Category < ApplicationRecord
  acts_as_paranoid
  has_many :products
  validates :title, presence: true

  def self.to_csv
    attributes = all.column_names
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |category|
        csv << attributes.map { |attr| category.send(attr) }
      end
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# Categories
class CategoriesController < ApplicationController
  include ImportExport

  before_action :authenticate_user!
  before_action :find_category, only: %i[show edit update destroy]
  before_action :filter_object_ids, only: %i[bulk_method restore]
  before_action :klass_bulk_method, only: %i[bulk_method]
  before_action :klass_restore, only: %i[restore]

  def index
    @category_exports = ExportMapping.where(table_name: 'Category')
    @q = Category.ransack(params[:q])
    @categories = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(params[:limit])
    export_csv(@categories) if params[:export_csv].present?

    generate_pdf if params[:format].eql? 'pdf'
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created successfully.'
      redirect_to categories_path
    else
      flash.now[:notice] = 'Category not created.'
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated successfully.'
      redirect_to categories_path
    else
      flash.now[:notice] = 'Category not updated.'
      render 'edit'
    end
  end

  def version
    @versions = Category.find_by(id: params[:id])&.versions
  end

  def destroy
    if @category.destroy
      flash[:notice] = 'Category archive successfully.'
      redirect_to categories_path
    else
      flash.now[:notice] = 'Category not archived.'
      render categories_path
    end
  end

  def export_csv(categories)
    categories = categories.where(selected: true) if params[:selected]
    if params[:export_mapping].present?
      @export_mapping = ExportMapping.find(params[:export_mapping])
      attributes = @export_mapping.export_data
      @csv = CSV.generate(headers: true) do |csv|
        csv << attributes
        categories.each do |category|
          csv << attributes.map { |attr| category.send(attr) }
        end
      end
      request.format = 'csv'
      respond_to do |format|
        format.csv { send_data @csv, filename: "categories-#{Date.today}.csv" }
      end
    else
      request.format = 'csv'
      respond_to do |format|
        format.csv { send_data categories.to_csv, filename: "categories-#{Date.today}.csv" }
      end
    end
  end

  def generate_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'file.pdf', viewport_size: '1280x1024', template: 'categories/index.pdf.erb'
      end
    end
  end

  def bulk_method
    redirect_to categories_path
  end

  def archive
    @q = Category.only_deleted.ransack(params[:q])
    @categories = @q.result(distinct: true).page(params[:page]).per(params[:limit])
  end

  def restore
    redirect_to archive_categories_path
  end

  def permanent_delete
    flash[:notice] = if params[:object_id].present? && Category.only_deleted.find(params[:object_id]).really_destroy!
                       'Category deleted successfully'
                     else
                       'Category cannot be deleted/Please select something to delete'
                     end
    redirect_to archive_categories_path
  end

  def search_category_by_title
    @searched_category_by_title = Category.ransack('title_cont': params[:search_value].downcase.to_s)
                                          .result.limit(20).pluck(:id, :title)
    respond_to do |format|
      format.json { render json: @searched_category_by_title }
    end
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/views/categories/archive.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Categories</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= settings_path %>">Settings</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="<%= categories_path %>">Categories</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Archive</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->

<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <div class='mr-1 float-right'>
            <%= link_to 'Categories', categories_path, class: 'btn btn-outline-info' %>
          </div>
          <h5 class="card-title"> Data</h5>
        </div>
        <%= search_form_for @q, url: archive_categories_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>
              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#archive-modal'>Restore</a>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#delete-modal'>Permanent Delete</a>
              </div>
            </div>
            <div class="col-md-2"><br>
              <%= f.search_field :title_cont, class:"form-control", placeholder:"Search in title" %>
            </div>
            <div class='col-1 offset-8'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([5, 10, 15, 20], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div>
        <% end %>
        <br>
        <%= form_with url: restore_categories_path , method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <tr>
                <th><input type="checkbox" id="" name="" value="" class='select-all-checkbox'></th>
                <th class="text-center">Tilte</th>
                <th class="text-center">Description</th>
                <th colspan="3" class="text-center">Actions</th>
              </tr>
              <% @categories&.each&.with_index(1) do |category, index| %>
                <tr class=''>
                  <td><%= f.check_box 'object_ids[]', {}, category.id %></td>
                  <td class="text-center"><%= category.title %></td>
                  <td class="text-center"><%= category.description %></td>
                  <td class="text-center">
                    <div class="dropdown dropleft">
                        <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <i class='lni lni-more-alt'></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <%= link_to 'Restore', restore_categories_path(object_id: category), method: :post, data: {confirm: "Are you sure you want to restore"}, class: "dropdown-item"%>
                          <%= link_to 'Permanent Delete', permanent_delete_categories_path(object_id: category), method: :post, data: {confirm: "Are you sure you want to parmanent delete"}, class: "dropdown-item"%>
                        </div>
                      </div>
                  </td>
                </tr>
              <% end %>
              <%= f.submit 'Restore', class: 'bulk-method-delete-objects d-none'%>
              <%= f.submit 'Delete', class: 'bulk-method-destroy-objects d-none'%>
            </table>
          </div>
        <% end %>
        <br>
        <div class='float-right'>
          <%= page_entries_info @categories %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @categories,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="archive-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want restore selected categories?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger bulk-delete-objects">Confirm</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want permanent delete selected categories?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger bulk-destroy-objects">Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Categories</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= settings_path %>">Settings</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="<%= categories_path %>">Categories</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="<%= category_path(@category) %>">Category</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Edit</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <h5 class="card-title">Edit</h5>
        </div>
        <%= form_for @category, url: category_path(@category) do |f| %>
          <%= render 'form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Categories</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= settings_path %>">Settings</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Categories</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="alert alert-dismissible fade show text-white jquery-selected-alert d-none " style="position: fixed; width:93%; z-index:99999;" role="alert"></div>
<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <a href="/categories/new" class="btn btn-primary float-right">Create</a>
          <div class='mr-1 float-right'>
            <%= link_to 'PDF', categories_path(format: :pdf), class:"btn btn-primary float-right ml-1", type:"button"%>
          </div>
          <div class="mr-1 float-right dropdown">
            <button class="btn btn-outline-primary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Export
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Export All', categories_path(all: true, format: :csv, export_csv: true), class: 'dropdown-item' %>
              <%= link_to 'Export Selected', categories_path(selected: true, format: :csv, export_csv: true), class: 'dropdown-item' %>
              <% @category_exports.each do |export| %>
                <%= link_to "#{export.sub_type}", categories_path(export_mapping: export.id, format: :csv, export_csv: true), class: 'dropdown-item' %>
              <% end %>
            </div>
          </div>
          <div class='mr-1 float-right'>
            <%= link_to 'Archives', archive_categories_path, class: 'btn btn-outline-info' %>
          </div>
          <h5 class="card-title"> Data</h5>
        </div>
        <%= search_form_for @q, url: categories_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>
              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#archive-modal'>Archive</a>
              </div>
            </div>
            <div class="col-md-3"><br>
              <div class="dropdown">
                <%= f.search_field :title_cont, class: 'form-control dropdown-toggle', id: 'category-title-search', data: {toggle: 'dropdown'}, area: {haspopup: true, expanded: 'false'}, autocomplete: 'off', placeholder:"Search in title", onkeyup: "dropdown_search( '/categories/category_by_title', 'category-dropdown-list', 'category-list-item', event)", onclick: "dropdown_search( '/categories/category_by_title', 'category-dropdown-list', 'category-list-item', event)" %>
                <span class="searchclear">@@</span>
                <ul class="dropdown-menu category-dropdown-list search-list" aria-labelledby="category-title-search">
                  <li><a href="#" class="dropdown-item category-list-item">Select Category</a></li>
                </ul>
              </div>
            </div>
            <div class='col-1 offset-7'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([5, 10, 15, 20], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div>
        <% end %>
        <br>
        <%= form_with url: bulk_method_categories_path , method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <tr>
                <th>
                  <div class='row' style='max-width: 65px'>
                    <div class='col-6 p-0'>
                      <div class="custom-control custom-switch">
                        <input type="checkbox" class="selectSwitchAll" id="selectSwitchAll" style= 'width:25px; height:25px;' onclick="bulk_update_selected('/bulk_update_selected', '<%= @categories&.first&.class&.name %>', event)">
                        <label for="selectSwitchAll"></label>
                      </div>
                    </div>
                  </div>
                </th>
                <th class="text-center">Tilte</th>
                <th class="text-center">Description</th>
                <th colspan="3" class="text-center">Actions</th>
              </tr>
              <% @categories&.each&.with_index(1) do |category, index| %>
                <tr class=''>
                  <td>
                    <div class='row' style='max-width: 65px'>
                      <div class='col-6 p-0'>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="selectSwitch" name="select-switch" style= 'width:25px; height:25px;' id="<%=category.id%>" <%= category.selected? ? 'checked': ''%> onclick="update_selected('/update_selected', '<%= category.class.name %>', event)">
                          <label for="<%=category.id%>"></label>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="text-center"><%= category.title %></td>
                  <td class="text-center"><%= category.description %></td>
                  <td class="text-center">
                    <div class="dropdown dropleft">
                        <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title='Actions'>
                          <i class='lni lni-more-alt'></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <%= link_to 'Logs',  version_categories_path(id: category.id), class: 'dropdown-item' %>
                          <a class="dropdown-item" href="<%= category_path(category)%>">View</a>
                          <%= link_to 'Archive', category_path(category), method: 'delete', data: {confirm: "Are you sure you want to archive"}, class: "dropdown-item"%>
                        </div>
                      </div>
                  </td>
                </tr>
              <% end %>
              <%= f.submit '', class: 'bulk-method-delete-objects d-none'%>
            </table>
          </div>
        <% end %>
        <br>
        <div class='float-right'>
          <%= page_entries_info @categories %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @categories,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="archive-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want archive selected categories?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger bulk-delete-objects">Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Categories</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= settings_path %>">Settings</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="<%= categories_path %>">Categories</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Create</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <h5 class="card-title">Create</h5>
        </div>
        <%= form_for @category, url: categories_path, method: :post do |f| %>
          <%= render 'form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>